name: comcat
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - impactutils
  - fiona==1.8.4
  - ipython
  - jupyter
  - numpy
  - obspy
  - pyproj
  - pandas
  - pip
  - pytest
  - pytest-cov
  - vcrpy
  - xlrd
  - xlwt
  - openpyxl
  - xlsxwriter